safe: true
name: 'Simon Sigurdhsson'
url: http://sigurdhsson.org/

future: false
permalink: /:categories/:year/:month/:title

markdown: rdiscount
pygments: true
rdiscount extensions: [smart,filter_styles]
